# .github/workflows/deploy.yml

name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Add known hosts
      run: |
        ssh-keyscan -H ${{ secrets.DO_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        scp -r . root@${{ secrets.DO_SERVER_IP }}:/var/www/lbal-back

    - name: SSH into server and run deploy script
      run: |
        ssh root@${{ secrets.DO_SERVER_IP }} "bash /var/www/lbal-back/deploy.sh"
