name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Or your preferred runner OS

    steps:
      - uses: actions/checkout@v3

      - name: Download DigitalOcean access token
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        run: |
          echo "$DIGITALOCEAN_ACCESS_TOKEN" > access_token.txt

      - name: Create temporary SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Private key from secret
          chmod 600 ~/.ssh/id_rsa
          echo " ${{ secrets.DO_SERVER_USERNAME }}@${{ secrets.DO_SERVER_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy to server (replace with your deployment commands)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: ${{ secrets.DO_SERVER_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DO_KEY_PHRASE }}
          script: |
            cd /var/www/lbal-back
            git pull
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts --no-dev --no-progress --no-plugins
            php artisan migrate:fresh
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan queue:restart


